# Generated by Django 5.1.2 on 2024-10-27 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('picture_link', models.TextField()),
                ('restaurant', models.CharField(max_length=90)),
                ('kategori', models.CharField(max_length=31)),
                ('lokasi', models.CharField(max_length=175)),
                ('price', models.PositiveIntegerField()),
                ('nutrition', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('link_gofood', models.TextField()),
                ('is_dataset_product', models.BooleanField(default=False)),
                ('bookmarked', models.ManyToManyField(blank=True, related_name='bookmarked_products', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
