# Generated by Django 4.2.16 on 2024-10-23 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('picture_link', models.TextField()),
                ('restaurant', models.CharField(max_length=63)),
                ('kategori', models.CharField(max_length=31)),
                ('lokasi', models.TextField()),
                ('price', models.IntegerField()),
                ('nutrition', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('link_gofood', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
