# Generated by Django 4.2.16 on 2024-10-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bookmarked',
        ),
    ]
