# Generated by Django 4.2.16 on 2024-10-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='lokasi',
            field=models.CharField(max_length=175),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='restaurant',
            field=models.CharField(max_length=90),
        ),
    ]
