# Generated by Django 4.2.16 on 2024-10-27 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('katalog', '0002_remove_product_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
