# Generated by Django 4.2.16 on 2024-10-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
