# Generated by Django 5.1.4 on 2024-12-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="title",
            field=models.CharField(default="Untitle", max_length=255),
        ),
    ]
