# Generated by Django 5.1.2 on 2024-10-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplan",
            name="time",
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
