# Generated by Django 5.1.2 on 2024-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("katalog", "0001_initial"),
        ("meal_planning", "0002_remove_mealplan_food_items_mealitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="food_items",
            field=models.ManyToManyField(to="katalog.product"),
        ),
        migrations.DeleteModel(
            name="MealItem",
        ),
    ]
