# Generated by Django 5.1.2 on 2024-10-24 15:48

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_planning", "0003_mealplan_food_items_delete_mealitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealplan",
            options={},
        ),
        migrations.AddField(
            model_name="mealplan",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="meal_type",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 10, 24, 15, 48, 31, 684565, tzinfo=datetime.timezone.utc
                ),
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mealplan",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2024, 10, 24, 15, 48, 42, 228581, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
