# Generated by Django 5.1.2 on 2024-10-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preference',
            field=models.CharField(max_length=100),
        ),
    ]
