# Generated by Django 5.1.2 on 2024-10-26 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumquestion',
            old_name='replies',
            new_name='replycount',
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='topic',
            field=models.CharField(choices=[('Information', 'Information'), ('Foods', 'Foods'), ('Restaurants', 'Restaurants'), ('Recommendation', 'Reccomendation'), ('Experience', 'Experience')], default='Information', max_length=25),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumquestion'),
        ),
    ]
