# Generated by Django 5.1.2 on 2024-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='topic',
            field=models.CharField(choices=[('Information', 'Information'), ('Foods', 'Foods'), ('Restaurants', 'Restaurants'), ('Recommendation', 'Rekomendasi'), ('Experience', 'Experience')], default='Information', max_length=25),
        ),
    ]
