# Generated by Django 5.1.2 on 2024-10-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumquestion_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumquestion',
            name='topic',
            field=models.CharField(choices=[('Information', 'Information'), ('Foods', 'Foods'), ('Restaurants', 'Restaurants'), ('Recommendation', 'Reccomendation'), ('Experience', 'Experience')], default='Information', max_length=25),
        ),
    ]
