# Generated by Django 5.1.2 on 2024-10-23 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forumquestion_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumquestion',
            old_name='replies',
            new_name='replycount',
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumquestion'),
        ),
    ]
