# Generated by Django 5.1.2 on 2024-10-26 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_replies_forumquestion_replycount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='topic',
            field=models.CharField(choices=[('Information', 'Information'), ('Foods', 'Foods'), ('Restaurants', 'Restaurants'), ('Recommendation', 'Recommendation'), ('Experience', 'Experience')], default='Information', max_length=25),
        ),
    ]
