# Generated by Django 5.1.2 on 2024-10-25 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_alter_product_description_alter_product_item_and_more'),
        ('rateNreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_views', to='katalog.product'),
        ),
    ]
